import React from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { 
  ShieldAlert, 
  ShieldCheck, 
  Activity, 
  FileText, 
  Sprout, 
  Layers, 
  RotateCcw,
  Sparkles,
  AlertTriangle,
  Info
} from 'lucide-react';
import BackButton from '../components/BackButton';
import DisclaimerBanner from '../components/DisclaimerBanner';
import { useCropAnalysis } from '../context/CropAnalysisContext';
import { getFullImageUrl } from '../services/api';

export default function Analysis() {
  const navigate = useNavigate();
  const { currentImage, analysisResult, isAnalyzing, analysisError } = useCropAnalysis();

  if (isAnalyzing) {
    return (
      <div className="max-w-2xl mx-auto px-4 py-20 text-center">
        <div className="w-20 h-20 mx-auto mb-6 rounded-2xl bg-emerald-950/60 border border-emerald-500/40 flex items-center justify-center animate-pulse-glow">
          <Sparkles className="w-10 h-10 text-emerald-400 animate-spin" />
        </div>
        <h2 className="text-2xl font-bold text-white mb-2">Analyzing Crop...</h2>
        <p className="text-sm text-slate-400 max-w-md mx-auto leading-relaxed">
          OpenCV is evaluating foliar features, and the Attentive Convolutional Recurrent Network is localizing pathology markers.
        </p>
      </div>
    );
  }

  if (!analysisResult) {
    return (
      <div className="max-w-md mx-auto px-4 py-16 text-center">
        <BackButton defaultTo="/scanner" label="Scanner" className="mb-6" />
        <div className="p-8 rounded-2xl bg-slate-900 border border-slate-800">
          <Activity className="w-12 h-12 text-slate-600 mx-auto mb-4" />
          <h2 className="text-lg font-bold text-white mb-2">No Active Analysis</h2>
          <p className="text-xs text-slate-400 mb-6">
            Please scan or upload a crop photograph to inspect plant health and generate diagnostic findings.
          </p>
          <button
            onClick={() => navigate('/scanner')}
            className="w-full py-2.5 rounded-xl text-xs font-semibold bg-emerald-600 hover:bg-emerald-500 text-white transition-colors"
          >
            Go to Crop Scanner
          </button>
        </div>
      </div>
    );
  }

  const isHealthy = analysisResult.health_status === 'Healthy';
  const displayImage = currentImage ? getFullImageUrl(currentImage) : null;

  // Severity color indicator
  const getSeverityBadge = (severity) => {
    switch ((severity || '').toLowerCase()) {
      case 'severe':
        return <span className="px-3 py-1 rounded-full text-xs font-bold bg-rose-950/80 text-rose-300 border border-rose-600/40">Severe</span>;
      case 'moderate':
        return <span className="px-3 py-1 rounded-full text-xs font-bold bg-amber-950/80 text-amber-300 border border-amber-600/40">Moderate</span>;
      case 'low':
        return <span className="px-3 py-1 rounded-full text-xs font-bold bg-teal-950/80 text-teal-300 border border-teal-600/40">Low</span>;
      default:
        return <span className="px-3 py-1 rounded-full text-xs font-bold bg-emerald-950/80 text-emerald-300 border border-emerald-600/40">None (Healthy)</span>;
    }
  };

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 py-6 sm:py-10">
      {/* Header with Back button to Scanner */}
      <div className="flex items-center justify-between gap-4 mb-6">
        <BackButton defaultTo="/scanner" label="Scanner" />
        <div className="text-right">
          <h1 className="text-xl sm:text-2xl font-bold text-white tracking-tight">Crop Analysis</h1>
          <p className="text-xs text-slate-400">Diagnostic summary generated by ACRNN</p>
        </div>
      </div>

      <DisclaimerBanner 
        isDemoMode={analysisResult.is_demo_mode} 
        isLowConfidence={analysisResult.is_low_confidence}
        warningMessage={analysisResult.confidence_warning}
      />

      {/* Main Analysis Summary Card */}
      <div className="grid grid-cols-1 md:grid-cols-12 gap-6 bg-slate-900 border border-slate-800 rounded-3xl p-6 sm:p-8 shadow-2xl mb-8">
        
        {/* Left Column: Image Preview */}
        <div className="md:col-span-5 flex flex-col items-center justify-center">
          <div className="relative w-full rounded-2xl overflow-hidden border border-slate-700 bg-slate-950 aspect-square shadow-inner">
            {displayImage ? (
              <img
                src={displayImage}
                alt="Analyzed Crop Leaf"
                className="w-full h-full object-cover"
              />
            ) : (
              <div className="w-full h-full flex items-center justify-center text-slate-600 text-xs">
                No preview image available
              </div>
            )}
            <div className="absolute bottom-3 left-3 px-2 py-1 rounded bg-slate-900/80 backdrop-blur-md text-[10px] font-mono text-slate-300 border border-slate-700">
              {analysisResult.crop_category || 'Plant Specimen'}
            </div>
          </div>
        </div>

        {/* Right Column: AI Diagnostic Findings Summary */}
        <div className="md:col-span-7 flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between mb-4">
              <span className="text-xs font-mono font-semibold tracking-wider text-emerald-400 uppercase">
                AI ANALYSIS SUMMARY
              </span>
              <span className="text-xs font-mono text-slate-400">
                {analysisResult.model_mode || 'ACRNN'}
              </span>
            </div>

            {/* Crop Detected */}
            <div className="mb-4">
              <span className="text-xs text-slate-400 block mb-1">Detected Crop</span>
              <div className="text-2xl sm:text-3xl font-extrabold text-white flex items-center gap-2">
                <span>{analysisResult.crop}</span>
                <span className="text-xs font-normal text-slate-400 font-mono">({analysisResult.crop_category})</span>
              </div>
            </div>

            {/* Health Status & Disease Badge */}
            <div className="grid grid-cols-2 gap-4 p-4 rounded-2xl bg-slate-950/60 border border-slate-800 mb-6">
              <div>
                <span className="text-[11px] text-slate-400 block mb-1">Health Status</span>
                <div className="flex items-center gap-2">
                  {isHealthy ? (
                    <ShieldCheck className="w-5 h-5 text-emerald-400" />
                  ) : (
                    <ShieldAlert className="w-5 h-5 text-rose-400" />
                  )}
                  <span className={`text-sm font-bold ${isHealthy ? 'text-emerald-300' : 'text-rose-300'}`}>
                    {analysisResult.health_status}
                  </span>
                </div>
              </div>

              <div>
                <span className="text-[11px] text-slate-400 block mb-1">Identified Disease</span>
                <span className="text-sm font-bold text-white block truncate">
                  {analysisResult.disease}
                </span>
              </div>

              <div>
                <span className="text-[11px] text-slate-400 block mb-1">Detection Confidence</span>
                <div className="flex items-center gap-2">
                  <span className="text-sm font-mono font-bold text-emerald-400">
                    {analysisResult.confidence}%
                  </span>
                  <div className="w-20 bg-slate-800 h-2 rounded-full overflow-hidden">
                    <div 
                      className={`h-full ${analysisResult.confidence > 70 ? 'bg-emerald-400' : 'bg-amber-400'}`}
                      style={{ width: `${Math.min(100, analysisResult.confidence)}%` }}
                    />
                  </div>
                </div>
              </div>

              <div>
                <span className="text-[11px] text-slate-400 block mb-1">Estimated Severity</span>
                <div>{getSeverityBadge(analysisResult.severity)}</div>
              </div>
            </div>
          </div>

          {/* Quick Notice */}
          <p className="text-xs text-slate-400 mb-4">
            This screen provides a preliminary AI diagnosis summary. Proceed to the dedicated pages below for the comprehensive health report, growth conditions, and soil management.
          </p>
        </div>
      </div>

      {/* Navigation Buttons to Dedicated Multi-Pages */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <button
          onClick={() => navigate('/health')}
          className="flex items-center justify-between p-4 rounded-2xl bg-emerald-950/40 hover:bg-emerald-950/70 border border-emerald-500/30 text-white font-semibold transition-all hover:scale-[1.02] shadow-lg group"
        >
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-emerald-500/20 flex items-center justify-center text-emerald-400">
              <FileText className="w-5 h-5" />
            </div>
            <div className="text-left">
              <div className="text-sm font-bold">Health Report</div>
              <div className="text-[11px] text-emerald-300/80">Symptoms & Causes</div>
            </div>
          </div>
        </button>

        <button
          onClick={() => navigate('/growth')}
          className="flex items-center justify-between p-4 rounded-2xl bg-teal-950/40 hover:bg-teal-950/70 border border-teal-500/30 text-white font-semibold transition-all hover:scale-[1.02] shadow-lg group"
        >
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-teal-500/20 flex items-center justify-center text-teal-400">
              <Sprout className="w-5 h-5" />
            </div>
            <div className="text-left">
              <div className="text-sm font-bold">Growth Guide</div>
              <div className="text-[11px] text-teal-300/80">Water, Light & Pests</div>
            </div>
          </div>
        </button>

        <button
          onClick={() => navigate('/soil')}
          className="flex items-center justify-between p-4 rounded-2xl bg-cyan-950/40 hover:bg-cyan-950/70 border border-cyan-500/30 text-white font-semibold transition-all hover:scale-[1.02] shadow-lg group"
        >
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-cyan-500/20 flex items-center justify-center text-cyan-400">
              <Layers className="w-5 h-5" />
            </div>
            <div className="text-left">
              <div className="text-sm font-bold">Soil Information</div>
              <div className="text-[11px] text-cyan-300/80">pH & Nutrient Targets</div>
            </div>
          </div>
        </button>

        <button
          onClick={() => navigate('/scanner')}
          className="flex items-center justify-between p-4 rounded-2xl bg-slate-800/80 hover:bg-slate-700/80 border border-slate-700 text-slate-200 font-semibold transition-all hover:scale-[1.02] shadow-lg group"
        >
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-slate-700/40 flex items-center justify-center text-slate-300">
              <RotateCcw className="w-5 h-5" />
            </div>
            <div className="text-left">
              <div className="text-sm font-bold">Back to Scanner</div>
              <div className="text-[11px] text-slate-400">Scan Another Plant</div>
            </div>
          </div>
        </button>
      </div>
    </div>
  );
}
